boat_param:
    longitudinal_drag: 0.1
    lateral_drag: 2
    longitudinal_noise_var: 0.1
    lateral_noise_var: 0.01
control_param:
    max_thrust: 2
    max_rudder_angle: 5      # in degree
    thrust_input_type: 0      # 0=step, 1=sin
    rudder_input_type: 0
    Ts: 0.5                   # control sampling time
sim_param:
    Ts: 0.1                   # simulation time
meas_param:
    sigma_a: 4.472            # sigma^2 = 20
    sigma_b: 4.472            # sigma^2 = 20
    sigma_c: 2.236            # sigma^2 = 5
    loss_probability_c: 0.2   # measurement from c is not always available
    sigma_g: 0.1              # sigma^2 = 0.01
    sigma_n: 0.7071           # sigma^2 = 0.5
    drift_stdev: 0.1          # Q_b = 0.01
    pos_a: [-1000.0,1000.0]
    pos_b: [2000.0, 0.0]
    pos_c: [0, -2000.0]


